config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  resources :users do
    resources :characters
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :characters
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    def username    
    return self.email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
  end

  def new
    @user = User.find(params[:user_id])
    @character = @user.characters.new
    render :new
  end

  def create
    @user = User.find(params[:user_id])
    @character = @user.characters.new(character_params)
    if @character.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:user_id])
    @character = Character.find(params[:id])
    render :show
  end

  def edit
    @user = User.find(params[:user_id])
    @character = Character.find(params[:id])
    render :edit
  end

  def update
    @character = Character.find(params[:id])
    if @character.update(character_params)
      redirect_to user_path(@character.user)
    else
      @user = User.find(params[:user_id])
      render :edit
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to user_path(@character.user)
  end

  private
    def character_params
      params.require(:character).permit(:war_name, :war_race, :war_class, :war_cost, :war_strength)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :only => [:new, :edit, :create, :update, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User successfully created!"
      redirect_to users_path
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def show
    @user = User.find(params[:id])
    render :show
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User successfully updated!"
      redirect_to new_user_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User successfully DESTROYED!!"
    redirect_to users_path
  end

  def home
  
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :resource)
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/edit.html.erb
<h1>Edit Character</h1>

<%= render "layouts/character_form" %>

app/views/characters/index.html.erb
<h1>Characters#Index</h1>


<%= link_to "HOME PAGE", "/" %>

app/views/characters/new.html.erb
<h1>Character Form</h1>

<%= render "layouts/character_form" %>

app/views/characters/show.html.erb
<h1>Character: <%= @character.war_name %></h1>
<h2>User: <%= @user.email %></h2>
<h3>War Race: <%= @character.war_race %></h3>
<h3>War Class: <%= @character.war_class %></h3>
<h3>War Cost: <%= @character.war_cost %></h3>
<h3>War Strength: <%= @character.war_strength %></h3>

<p><%= link_to "Edit character", edit_user_character_path(@user, @character) %></p>
<p><%= link_to "Delete character", user_character_path(@user, @character),
                                  :data => {:confirm => "Are you sure?",
                                                    :method => "delete"} %></p>

<p><%= link_to "Return to User", user_path(@user) %></p>

app/views/home/index.html.erb
<h1> Home Page </h1>

app/views/layouts/_character_form.html.erb
<%= render "layouts/errors", :object => @character %>

<%= form_for [@user, @character] do |f| %>
  <%= f.label :war_name %>
  <%= f.text_field :war_name %>
  <%= f.label :war_race %>
  <%= f.select :war_race, [["Blood Elf", "Blood Elf"],["Dragon Turtle", "Dragon Turtle"],["Chimera", "Chimera"], ["Troll", "Troll"]] %>
  <%= f.label :war_class %>
  <%= f.select :war_class, [["Beasts of Chaos", "Beasts of Chaos"], ["Vampire Counts", "Vampire Counts"], ["Warlock", "Warlock"]] %>
  <%= f.label :war_cost %>
  <%= f.number_field :war_cost %>
  <%= f.label :war_strength %>
  <%= f.number_field :war_strength %>
  <%= f.submit %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <p><%= link_to "Return to homepage", home_path, class: "btn btn-default" %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWorldWarhammer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class='registration'>
    <%= link_to "Home", "/"%>
    <% if user_signed_in? %>
      
      <%= link_to "Edit Account", edit_user_registration_path %>
      <%= current_user.email %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      
    <% else %>
      <p><%= link_to "Sign-In/Sign-Up", new_user_session_path %></p>
    <% end %>
  </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1> Users#Index </h1>

<% if @users.any? %>
  <ul>
    <% @users.each do |user| %>
      <li><%= link_to user.username, user_path(user) %></li>
    <% end %> 
  </ul>
<% else %>
  <p>There are no users.</p>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<% if @user.characters.any? %>
  <h4>Here are the characters for this user:<h4>

  <% @user.characters.each do |char| %>
    <ul>
      <li>
        <%= link_to char.war_name, user_character_path(@user, char) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No characters for this user.</p>
<% end %>

<p><%= link_to "Add a character", new_user_character_path(@user) %></p>

<p><%= link_to "Edit", edit_user_path(@user) %></p>
<p><%= link_to "Delete", user_path(@user),
                          :data => {:comfirm => "You sure?",
                                    :method => "delete"} %></p>

<p><%= link_to "Return to users", users_path %></p>